name: Finance deploy stage

on:
  push:
    branches: [main]
    paths:
      - "apps/finance/**"
      - ".github/workflows/finance-deploy-stage.yml"
      - ".github/workflows/deploy.yml"

concurrency:
  group: deploy-stage-finance
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      app: finance
      environment: stage
      port: "8001"
    secrets: inherit
